### ISSUE TITLE
Add `revert` type

### ISSUE THREAD

**Issue by beeb** [convco/convco#309]
**Is your feature request related to a problem? Please describe.**
The spec describes a `revert:` commit type which is not available in `convco commit`

**Describe the solution you'd like**
Add a `revert:` commit type to the type prompt

**Describe alternatives you've considered**
Using `commitizen` which supports this type

**Additional context**
N/A

**Comment by hdevalke** [comment]
Sorry to answer late.
You can always create custom types in a `.convco` config file. e.g.:

```yaml
types:
- type: revert
  section: Revert
  hidden: false
- type: feat
  section: Features
  hidden: false
- type: fix
  section: Fixes
  hidden: false
- type: build
  section: Other
  hidden: true
- type: chore
  section: Other
  hidden: true
- type: ci
  section: Other
  hidden: true
- type: docs
  section: Documentation
  hidden: true
- type: style
  section: Other
  hidden: true
- type: refactor
  section: Other
  hidden: true
- type: perf
  section: Other
  hidden: true
- type: test
  section: Other
  hidden: true
```

The problem with revert is that it complicates the next version calculation:

> Reverting code can be complicated: are you reverting multiple commits? if you revert a feature, should the next release instead be a patch?
>
> https://www.conventionalcommits.org/en/v1.0.0/#how-does-conventional-commits-handle-revert-commits

If you commit a feature and then revert it in a single release, should it even show the feature in the changelog?
